### ISSUE TITLE
Бесконечная загрузка при первом запуске

### ISSUE THREAD

**Issue by dEn13L** [khasang-incubator/Android_20151115#259]
При первом запуске после установки на Android 6 и разрешения гео пермишена, погода грузится бесконечно и в тулбаре заголово "Smart Forecast"

**Comment by dEn13L** [comment]
Stacktrace

07-27 10:28:19.750 32118-32118/com.khasang.forecast D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
07-27 10:28:19.766 32118-32118/com.khasang.forecast D/FirebaseApp: Initialized class com.google.firebase.iid.FirebaseInstanceId.
07-27 10:28:19.835 32118-32118/com.khasang.forecast D/ChimeraCfgMgr: Reading stored module config
07-27 10:28:19.850 32118-32118/com.khasang.forecast I/DynamiteModule: Considering local module com.google.android.gms.flags:0 and remote module com.google.android.gms.flags:1
07-27 10:28:19.850 32118-32118/com.khasang.forecast I/DynamiteModule: Selected remote version of com.google.android.gms.flags, version >= 1
07-27 10:28:19.867 32118-32118/com.khasang.forecast E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.android.gms.crash.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.khasang.forecast-1/base.apk"],nativeLibraryDirectories=[/data/app/com.khasang.forecast-1/lib/arm, /data/app/com.khasang.forecast-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
07-27 10:28:19.868 32118-32118/com.khasang.forecast I/DynamiteModule: Considering local module com.google.android.gms.crash:0 and remote module com.google.android.gms.crash:3
07-27 10:28:19.868 32118-32118/com.khasang.forecast I/DynamiteModule: Selected remote version of com.google.android.gms.crash, version >= 3
07-27 10:28:19.876 32118-32118/com.khasang.forecast W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi-v7a
07-27 10:28:19.876 32118-32118/com.khasang.forecast W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi
07-27 10:28:19.877 32118-32118/com.khasang.forecast D/ChimeraFileApk: Primary ABI of requesting process is armeabi-v7a
07-27 10:28:19.878 32118-32118/com.khasang.forecast D/ChimeraFileApk: Classloading successful. Optimized code found.
07-27 10:28:19.885 32118-32118/com.khasang.forecast I/FirebaseCrashApiImpl: FirebaseCrashApiImpl created by ClassLoader com.google.android.chimera.container.internal.DelegateLastPathClassLoader[DexPathList[[zip file "/data/data/com.google.android.gms/app_chimera/m/00000008/DynamiteModulesC_GmsCore_prodmnc_xxhdpi_release.apk"],nativeLibraryDirectories=[/data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi-v7a, /data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi, /vendor/lib, /system/lib]]]
07-27 10:28:19.895 32118-32118/com.khasang.forecast I/DynamiteModule: Considering local module com.google.android.gms.flags:0 and remote module com.google.android.gms.flags:1
07-27 10:28:19.895 32118-32118/com.khasang.forecast I/DynamiteModule: Selected remote version of com.google.android.gms.flags, version >= 1
07-27 10:28:19.910 32118-32118/com.khasang.forecast D/FirebaseCrashApiImpl: FirebaseCrash reporting API initialized
07-27 10:28:19.910 32118-32118/com.khasang.forecast I/FirebaseCrash: FirebaseCrash reporting initialized com.google.firebase.crash.internal.zzg@9fa6ff9
07-27 10:28:19.910 32118-32118/com.khasang.forecast D/FirebaseApp: Initialized class com.google.firebase.crash.FirebaseCrash.
07-27 10:28:19.921 32118-32118/com.khasang.forecast I/FA: App measurement is starting up, version: 9080
07-27 10:28:19.921 32118-32118/com.khasang.forecast I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
07-27 10:28:19.921 32118-32118/com.khasang.forecast D/FA: Debug logging enabled
07-27 10:28:19.922 32118-32118/com.khasang.forecast D/FA: AppMeasurement singleton hash: 8506783
07-27 10:28:19.939 32118-32118/com.khasang.forecast D/FirebaseApp: Initialized class com.google.android.gms.measurement.AppMeasurement.
07-27 10:28:19.940 32118-32118/com.khasang.forecast I/FirebaseInitProvider: FirebaseApp initialization successful
07-27 10:28:19.962 2767-2767/com.android.systemui D/PhoneStatusBar: disable: < expand icons\* alerts system_info\* back home recent clock search quick_settings >
07-27 10:28:20.003 32118-32118/com.khasang.forecast I/CrashlyticsCore: Initializing Crashlytics 2.3.8.97
07-27 10:28:20.025 32118-32165/com.khasang.forecast I/stetho: Listening on @stetho_com.khasang.forecast_devtools_remote
07-27 10:28:20.075 32118-32118/com.khasang.forecast D/TAG: showWelcome: true
07-27 10:28:20.075 32118-32118/com.khasang.forecast D/TAG: showWelcomeString: true
07-27 10:28:20.103 32118-32167/com.khasang.forecast D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-27 10:28:20.164 32118-32167/com.khasang.forecast I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (Ia6c73e7530)
                                                                  OpenGL ES Shader Compiler Version: E031.29.00.00
                                                                  Build Date: 12/04/15 Fri
                                                                  Local Branch: mybranch17080070
                                                                  Remote Branch: quic/LA.BF.1.1.3_rb1.5
                                                                  Local Patches: NONE
                                                                  Reconstruct Branch: NOTHING
07-27 10:28:20.181 32118-32167/com.khasang.forecast I/OpenGLRenderer: Initialized EGL, version 1.4
07-27 10:28:20.261 32118-32154/com.khasang.forecast W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
07-27 10:28:20.287 812-3344/system_process I/ActivityManager: Process com.maildroid (pid 649) has died
07-27 10:28:20.291 812-3344/system_process W/ActivityManager: Scheduling restart of crashed service com.maildroid/.service.KeepUsAliveService in 33043ms
07-27 10:28:20.295 812-1570/system_process I/ActivityManager: Displayed com.khasang.forecast/.activities.SplashScreenActivity: +748ms
07-27 10:28:20.717 3183-3183/com.google.android.inputmethod.latin I/DownloadManagerWrapper: onReceive() : Charging = true
07-27 10:28:20.719 4843-5085/com.android.bluetooth D/HeadsetStateMachine: Disconnected process message: 10, size: 0
07-27 10:28:20.723 6831-6831/org.zooper.zwfree D/ZWSleepReceiver: Received: android.intent.action.BATTERY_CHANGED
07-27 10:28:20.997 812-2692/system_process D/ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 176] to 60
07-27 10:28:21.942 5264-5326/com.google.android.youtube W/YouTube: Final ping for playback PXzDpqUFt9fXAtiD has already been sent - Ignoring request
07-27 10:28:22.491 812-2890/system_process I/ActivityManager: START u0 {flg=0x14000000 cmp=com.khasang.forecast/.activities.WeatherActivity} from uid 10423 on display 0
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err: com.khasang.forecast.exceptions.AccessFineLocationNotGrantedException
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.location.CurrentLocationManager.getLastLocation(CurrentLocationManager.java:53)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.position.PositionManager.initLocationManager(PositionManager.java:690)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.position.PositionManager.initManager(PositionManager.java:130)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.position.PositionManager.getInstance(PositionManager.java:112)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.activities.WeatherActivity.onCreate(WeatherActivity.java:136)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at android.app.Activity.performCreate(Activity.java:6251)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-27 10:28:22.579 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
07-27 10:28:22.580 32118-32118/com.khasang.forecast W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-27 10:28:22.580 32118-32118/com.khasang.forecast W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-27 10:28:22.580 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5466)
07-27 10:28:22.580 32118-32118/com.khasang.forecast W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-27 10:28:22.580 32118-32118/com.khasang.forecast W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-27 10:28:22.580 32118-32118/com.khasang.forecast W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-27 10:28:22.702 258-2217/? D/audio_hw_primary: out_standby: enter: stream (0xb60774c0) usecase(1: low-latency-playback)
07-27 10:28:22.743 32118-32152/com.khasang.forecast W/art: Long monitor contention event with owner method=long com.android.org.conscrypt.NativeCrypto.RSA_generate_key_ex(int, byte[]) from NativeCrypto.java:4294967294 waiters=0 for 2.489s
07-27 10:28:22.745 32118-32168/com.khasang.forecast W/InstanceID/Rpc: Found 10024
07-27 10:28:22.753 258-2217/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
07-27 10:28:22.776 6764-32229/com.google.android.gms D/FA-SVC: Setting user property: _fot, 1469595600000
07-27 10:28:22.779 6764-32229/com.google.android.gms D/FA-SVC: User property set: _fot, 1469595600000
07-27 10:28:22.783 24439-24691/com.google.android.gms.persistent D/GCM: GcmService start Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.c2dm.intent.REGISTER
07-27 10:28:22.835 812-3150/system_process I/ActivityManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.packageinstaller cmp=com.android.packageinstaller/.permission.ui.GrantPermissionsActivity (has extras)} from uid 10423 on display 0
07-27 10:28:22.850 32118-32118/com.khasang.forecast D/AutoManageHelper: starting AutoManage for client 0 false false
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err: com.khasang.forecast.exceptions.AccessFineLocationNotGrantedException
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.location.CurrentLocationManager.updateCurrLocCoordinates(CurrentLocationManager.java:107)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.position.PositionManager.updateCurrentLocationCoordinates(PositionManager.java:706)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.position.PositionManager.updateWeather(PositionManager.java:466)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.activities.WeatherActivity.onRefresh(WeatherActivity.java:673)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at com.khasang.forecast.activities.WeatherActivity.onCreate(WeatherActivity.java:173)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at android.app.Activity.performCreate(Activity.java:6251)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-27 10:28:22.858 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
07-27 10:28:22.859 32118-32118/com.khasang.forecast W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-27 10:28:22.859 32118-32118/com.khasang.forecast W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-27 10:28:22.859 32118-32118/com.khasang.forecast W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5466)
07-27 10:28:22.859 32118-32118/com.khasang.forecast W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-27 10:28:22.859 32118-32118/com.khasang.forecast W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-27 10:28:22.859 32118-32118/com.khasang.forecast W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-27 10:28:22.863 32118-32118/com.khasang.forecast I/WeatherActivity: Weather is null!
07-27 10:28:22.867 32118-32118/com.khasang.forecast I/WeatherActivity: Weather is null!
07-27 10:28:22.871 32118-32118/com.khasang.forecast I/WeatherActivity: Weather is null!
07-27 10:28:22.876 32118-32118/com.khasang.forecast D/AutoManageHelper: onStart true {0=com.google.android.gms.internal.zznr$zza@e66bc31}
07-27 10:28:22.893 812-4008/system_process I/ActivityManager: Start proc 32232:com.android.packageinstaller/u0a13 for activity com.android.packageinstaller/.permission.ui.GrantPermissionsActivity
07-27 10:28:22.899 32118-32118/com.khasang.forecast I/WeatherActivity: Weather is null!
07-27 10:28:22.903 32118-32118/com.khasang.forecast I/WeatherActivity: Weather is null!
07-27 10:28:22.907 32118-32118/com.khasang.forecast I/WeatherActivity: Weather is null!

**Comment by dEn13L** [comment]
Кнопка обновления погоды не помогает

Погода появляется только после пересоздания WeatherActivity (перезапуск или смена языка)
